// @ts-check
// Prototype: autogenerated sidebar from docs/ + _category_.json (doc-linked labels).
// Rollback options:
//   sidebars.js.backup        — original manual sidebar (pre i18n experiment)
//   sidebars.js.manual.backup — doc-linked manual sidebar (previous step)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
